//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamsungTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public int id_equipo { get; set; }
        public string nombre { get; set; }
        public string sku { get; set; }
        public string disponibilidad { get; set; }
        public string camara { get; set; }
        public string procesador { get; set; }
        public string pantalla { get; set; }
        public string descripcion { get; set; }
        public string familia { get; set; }
        public string imagen_1 { get; set; }
        public string imagen_2 { get; set; }
        public string imagen_3 { get; set; }
        public string video_producto { get; set; }
        public string C3D_producto { get; set; }
        public string brochure { get; set; }
        public string fecha_creacion { get; set; }
    }
}
