//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamsungTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantelcel
    {
        public int id_plantelcel { get; set; }
        public string plantelcel1 { get; set; }
        public string pago { get; set; }
        public string categoria { get; set; }
        public string mensajes { get; set; }
        public string minutos { get; set; }
        public string internet { get; set; }
        public string redes { get; set; }
    }
}
