//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamsungTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class samsung_cliente
    {
        public int Id_cliente { get; set; }
        public string nombre { get; set; }
        public string perfil { get; set; }
        public string usuario { get; set; }
        public string email { get; set; }
        public string fecha_creacion { get; set; }
        public string estado { get; set; }
        public string sexo { get; set; }
        public Nullable<int> edad { get; set; }
    }
}
