//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamsungTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class samsung_vendedores
    {
        public int Id_vendedores { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string numero { get; set; }
        public string operador { get; set; }
        public string region { get; set; }
        public string fecha_creacion { get; set; }
    }
}
