//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamsungTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendedor
    {
        public int id_vendedor { get; set; }
        public string nombre { get; set; }
        public string sexo { get; set; }
        public string usuario { get; set; }
        public string edad { get; set; }
        public string imei { get; set; }
        public string operador { get; set; }
        public string region { get; set; }
        public string novendedor { get; set; }
    }
}
